global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: beer-map
    static_configs: [{targets: ['otel-collector:8889']}]
rule_files: [/etc/beer-map/alerts.yaml]
alerting:
  alertmanagers:
    - static_configs: [{targets: ['alertmanager:9093']}]

