{{- if .Values.networkPolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: beer-map}
spec:
  podSelector:
    matchLabels: {app.kubernetes.io/name: beer-map}
  policyTypes: [Ingress, Egress]
  ingress:
    - ports: [{protocol: TCP, port: 3000}]
  egress:
    - to:
        - podSelector:
            matchLabels: {app.kubernetes.io/name: beer-map-db}
      ports: [{protocol: TCP, port: 5432}]
    {{- if .Values.telemetry.enabled }}
    - to:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: observability}
          podSelector:
            matchLabels: {app.kubernetes.io/name: otel-collector}
      ports: [{protocol: TCP, port: 4318}]
    {{- end }}
    - to:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: kube-system}
      ports: [{protocol: UDP, port: 53}, {protocol: TCP, port: 53}]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: beer-map-migrate}
spec:
  podSelector:
    matchLabels: {app.kubernetes.io/name: beer-map-migrate}
  policyTypes: [Ingress, Egress]
  ingress: []
  egress:
    - to:
        - podSelector:
            matchLabels: {app.kubernetes.io/name: beer-map-db}
      ports: [{protocol: TCP, port: 5432}]
    - to:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: kube-system}
      ports: [{protocol: UDP, port: 53}, {protocol: TCP, port: 53}]
{{- end }}
