import type { ExpressionSpecification, StyleSpecification } from 'maplibre-gl';

const localName = (): ExpressionSpecification => ['coalesce', ['get', 'name:lv'], ['get', 'name']];

export const darkRigaStyle: StyleSpecification = {
  version: 8,
  name: 'Riga After Dark',
  glyphs: 'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf',
  sources: {
    openmaptiles: {
      type: 'vector',
      url: 'https://tiles.openfreemap.org/planet',
      attribution: '&copy; OpenStreetMap contributors &copy; OpenMapTiles',
    },
  },
  transition: { duration: 100, delay: 0 },
  layers: [
    {
      id: 'background',
      type: 'background',
      paint: { 'background-color': '#0b0e0d' },
    },
    {
      id: 'residential-land',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: ['==', ['get', 'class'], 'residential'],
      paint: { 'fill-color': '#101412', 'fill-opacity': 0.72 },
    },
    {
      id: 'industrial-land',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: ['match', ['get', 'class'], ['industrial', 'commercial', 'retail'], true, false],
      paint: { 'fill-color': '#111513', 'fill-opacity': 0.9 },
    },
    {
      id: 'woodland',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['==', ['get', 'class'], 'wood'],
      paint: { 'fill-color': '#101b16', 'fill-opacity': 0.92 },
    },
    {
      id: 'grassland',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['match', ['get', 'class'], ['grass', 'farmland', 'meadow'], true, false],
      paint: { 'fill-color': '#101914', 'fill-opacity': 0.78 },
    },
    {
      id: 'parks',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'park',
      paint: {
        'fill-color': '#112219',
        'fill-opacity': ['interpolate', ['linear'], ['zoom'], 9, 0.74, 15, 0.94],
      },
    },
    {
      id: 'water',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'water',
      paint: { 'fill-color': '#07171c' },
    },
    {
      id: 'waterways',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'waterway',
      paint: {
        'line-color': '#0b252d',
        'line-width': ['interpolate', ['linear'], ['zoom'], 9, 0.45, 16, 2.2],
      },
    },
    {
      id: 'buildings',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'building',
      minzoom: 12,
      paint: {
        'fill-color': ['interpolate', ['linear'], ['zoom'], 12, '#151917', 16, '#1b211e'],
        'fill-outline-color': '#262d29',
        'fill-opacity': ['interpolate', ['linear'], ['zoom'], 12, 0.25, 15, 0.86],
      },
    },
    {
      id: 'paths',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 13,
      filter: ['match', ['get', 'class'], ['path', 'track'], true, false],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#262b28',
        'line-width': ['interpolate', ['linear'], ['zoom'], 13, 0.35, 17, 1.5],
        'line-opacity': 0.72,
        'line-dasharray': [1.3, 1.3],
      },
    },
    {
      id: 'minor-road-casing',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 12,
      filter: ['match', ['get', 'class'], ['minor', 'service'], true, false],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#080a09',
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 12, 0.6, 18, 9],
      },
    },
    {
      id: 'minor-roads',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 12,
      filter: ['match', ['get', 'class'], ['minor', 'service'], true, false],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#252a27',
        'line-width': ['interpolate', ['exponential', 1.4], ['zoom'], 12, 0.3, 18, 7],
      },
    },
    {
      id: 'major-road-casing',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['match', ['get', 'class'], ['tertiary', 'secondary', 'primary', 'trunk', 'motorway'], true, false],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#090b0a',
        'line-width': ['interpolate', ['exponential', 1.35], ['zoom'], 8, 1.2, 18, 15],
      },
    },
    {
      id: 'major-roads',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['match', ['get', 'class'], ['tertiary', 'secondary', 'primary', 'trunk', 'motorway'], true, false],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': [
          'match',
          ['get', 'class'],
          ['motorway', 'trunk'], '#3d3c32',
          ['primary', 'secondary'], '#343630',
          '#2b2f2b',
        ],
        'line-width': ['interpolate', ['exponential', 1.35], ['zoom'], 8, 0.7, 18, 12],
      },
    },
    {
      id: 'rail',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 11,
      filter: ['==', ['get', 'class'], 'rail'],
      paint: {
        'line-color': '#343a36',
        'line-width': ['interpolate', ['linear'], ['zoom'], 11, 0.45, 16, 1.2],
        'line-dasharray': [2, 2],
        'line-opacity': 0.72,
      },
    },
    {
      id: 'administrative-boundaries',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'boundary',
      filter: ['<=', ['get', 'admin_level'], 6],
      paint: {
        'line-color': '#3c4540',
        'line-width': ['interpolate', ['linear'], ['zoom'], 4, 0.45, 12, 1.2],
        'line-dasharray': [2, 2],
        'line-opacity': 0.42,
      },
    },
    {
      id: 'water-labels',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'water_name',
      minzoom: 9,
      layout: {
        'text-field': localName(),
        'text-font': ['Noto Sans Italic'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 9, 10, 15, 12],
        'text-letter-spacing': 0.08,
      },
      paint: {
        'text-color': '#365760',
        'text-halo-color': '#07171c',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'road-labels',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'transportation_name',
      minzoom: 13,
      filter: ['match', ['get', 'class'], ['minor', 'tertiary', 'secondary', 'primary', 'trunk'], true, false],
      layout: {
        'symbol-placement': 'line',
        'text-field': localName(),
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 13, 10, 17, 12.5],
        'text-letter-spacing': 0.02,
        'text-max-angle': 30,
        'text-padding': 8,
      },
      paint: {
        'text-color': '#858e88',
        'text-halo-color': '#101311',
        'text-halo-width': 1.4,
        'text-halo-blur': 0.3,
      },
    },
    {
      id: 'neighbourhood-labels',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      minzoom: 10,
      maxzoom: 16,
      filter: ['match', ['get', 'class'], ['suburb', 'quarter', 'neighbourhood'], true, false],
      layout: {
        'text-field': localName(),
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 10, 10, 15, 13],
        'text-letter-spacing': 0.13,
        'text-transform': 'uppercase',
        'text-padding': 18,
      },
      paint: {
        'text-color': '#59635d',
        'text-halo-color': '#0b0e0d',
        'text-halo-width': 1.4,
      },
    },
    {
      id: 'city-labels',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['match', ['get', 'class'], ['city', 'town'], true, false],
      layout: {
        'text-field': localName(),
        'text-font': ['Noto Sans Bold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 5, 13, 12, 20],
        'text-letter-spacing': 0.04,
        'text-padding': 24,
      },
      paint: {
        'text-color': '#aeb6b1',
        'text-halo-color': '#0b0e0d',
        'text-halo-width': 1.8,
      },
    },
  ],
};
