type Beer = { name: string; volumeMl: number | null; price: number };
type DayHours = string[] | null;
type Hours = {
  mon: DayHours; tue: DayHours; wed: DayHours; thu: DayHours;
  fri: DayHours; sat: DayHours; sun: DayHours; sourceUrl: string;
};
type ResearchedVenue = {
  id: string; name: string; kind: string; address: string; lat: number; lng: number;
  sourceUrl: string; sourceLabel: string;
  sourceType: 'Oficiālā ēdienkarte' | 'Verificēta aktuālā alus karte';
  beerPrices: Beer[]; hours: Hours; evidenceNotes: string;
};

const official = 'Oficiālā ēdienkarte' as const;

const venues: ResearchedVenue[] = [
  {
    id: 'lidl-arena-bar',
    name: 'Lidl Arena bārs',
    kind: 'sporta un pasākumu centra bārs',
    address: 'Kauguru iela 6, Rīga, LV-1046',
    lat: 56.9352538,
    lng: 24.0507639,
    sourceUrl: 'https://lidlarena.lv/kafe/',
    sourceLabel: 'Lidl Arena oficiālā aktuālā bāra ēdienkarte',
    sourceType: official,
    beerPrices: [
      { name: 'Corrona', volumeMl: 330, price: 4.5 },
      { name: 'Corrona Cero 0.0%', volumeMl: 330, price: 4.5 },
      { name: 'Leffe', volumeMl: 330, price: 4.5 },
      { name: 'Stella Artois (draft)', volumeMl: 500, price: 6 },
      { name: 'Piebalga (draft)', volumeMl: 500, price: 6 },
      { name: 'Pooka (draft)', volumeMl: 500, price: 6 },
    ],
    hours: {
      mon: ['09:00-23:30'], tue: ['09:00-23:30'], wed: ['09:00-23:30'], thu: ['09:00-23:30'],
      fri: ['09:00-23:30'], sat: ['09:00-23:30'], sun: ['09:00-23:30'],
      sourceUrl: 'https://wanderlog.com/place/details/7973890/lidl-arena',
    },
    evidenceNotes: 'First-party live 2026 page publishes the venue cafe menu, exact named beers, serving sizes, prices and address; the first-party site confirms on-premise beer after sport and events. The generic Alus and Bezalkoholiskais alus rows were excluded because no beer name is published. Weekly hours use the current venue listing because the first-party site only states that the arena opens every day. Coordinates match the mapped venue at Kauguru iela 6.',
  },
  {
    id: 'players-club-barona',
    name: 'Players Club — Barona',
    kind: 'izklaides un spēļu bārs',
    address: 'Krišjāņa Barona iela 31, Rīga, LV-1011',
    lat: 56.9535146,
    lng: 24.1255378,
    sourceUrl: 'https://lvplayersclub.lv/wp-content/uploads/2026/02/PlayersClub-Menu.pdf',
    sourceLabel: 'Players Club official 2026 drinks menu',
    sourceType: official,
    beerPrices: [
      { name: 'Bauskas (draft)', volumeMl: 500, price: 4.5 },
      { name: 'Salitos', volumeMl: 330, price: 4.5 },
      { name: 'Madonas nefiltrētais (draft)', volumeMl: 500, price: 5 },
      { name: 'Corona', volumeMl: 350, price: 5 },
    ],
    hours: {
      mon: ['17:00-23:00'], tue: ['17:00-23:00'], wed: ['17:00-23:00'], thu: ['17:00-23:00'],
      fri: ['13:00-02:00'], sat: ['12:00-02:00'], sun: ['12:00-21:00'],
      sourceUrl: 'https://lvplayersclub.lv/darba-laiks/',
    },
    evidenceNotes: 'The official Players Club menu page identifies the Barona branch and embeds its February 2026 drinks PDF with named beer prices and sizes. The official hours page publishes the branch schedule. The generic Beer/Cider in bottle row was excluded because it does not identify the beer.',
  },
  {
    id: 'players-club-xl-jekaba',
    name: 'Players Club XL — Jēkaba',
    kind: 'izklaides un spēļu bārs',
    address: 'Jēkaba iela 3/5, Rīga, LV-1050',
    lat: 56.9503066,
    lng: 24.1051076,
    sourceUrl: 'https://lvplayersclub.lv/wp-content/uploads/2026/02/PlayersClub-Menu.pdf',
    sourceLabel: 'Players Club official 2026 drinks menu',
    sourceType: official,
    beerPrices: [
      { name: 'Bauskas (draft)', volumeMl: 500, price: 4.5 },
      { name: 'Salitos', volumeMl: 330, price: 4.5 },
      { name: 'Madonas nefiltrētais (draft)', volumeMl: 500, price: 5 },
      { name: 'Corona', volumeMl: 350, price: 5 },
    ],
    hours: {
      mon: ['15:00-23:00'], tue: ['15:00-23:00'], wed: ['15:00-00:00'], thu: ['15:00-00:00'],
      fri: ['13:00-02:00'], sat: ['12:00-02:00'], sun: ['12:00-21:00'],
      sourceUrl: 'https://lvplayersclub.lv/darba-laiks/',
    },
    evidenceNotes: 'The official Players Club menu page identifies the Jēkaba branch and embeds its February 2026 drinks PDF with named beer prices and sizes. The official hours page publishes the branch schedule. The generic Beer/Cider in bottle row was excluded because it does not identify the beer.',
  },
  {
    id: 'stuora-bar',
    name: 'Stuora Bar',
    kind: 'kokteiļu bārs',
    address: 'Audēju iela 15, Rīga, LV-1050',
    lat: 56.9470315,
    lng: 24.1132973,
    sourceUrl: 'https://stuora.lv/en/',
    sourceLabel: 'Stuora Bar — official live menu',
    sourceType: official,
    beerPrices: [
      { name: 'Lager beer', volumeMl: 330, price: 5 },
    ],
    hours: {
      mon: [], tue: [], wed: [], thu: ['18:00-01:00'],
      fri: ['18:00-02:00'], sat: ['18:00-02:00'], sun: ['18:00-01:00'],
      sourceUrl: 'https://stuora.lv/en/',
    },
    evidenceNotes: 'The current official owner site identifies Stuora as a BarOrPub and publishes the complete beer section. Its embedded official Menu schema gives Lager beer 0.33L at EUR 5; the same page supplies the exact address, coordinates and weekly public hours.',
  },
  {
    id: 'runcis-krogs',
    name: 'Runcis krogs',
    kind: 'krogs',
    address: 'Jāņa sēta 1, Rīga, LV-1050',
    lat: 56.9479283,
    lng: 24.1109812,
    sourceUrl: 'https://www.google.com/maps/place/Runcis-krogs/@56.9480138,24.1109268,3a,75y,90t/data=!3m8!1e2!3m6!1sCIABIhBIFaTwS8ezjqwHwf2fBDGc!2e10!3e12!6shttps:%2F%2Flh3.googleusercontent.com%2Fgps-cs-s%2FAHRPTWnMFdxfUlTF7Qo2-v0YD4lG2kM5n_1FTi4ylrxcRYOKVsRktOiaIi0tvLhBlLWzZCvjyTQYzjx-RLL-Ey_icOHUWqJUmizaw9u_FaEzNVXc1GGQI-jFktfHtVRlY9Tov7g8j13HEs4W4Tg%3Dw141-h195-k-no!7i1062!8i1459!4m7!3m6!1s0x46eecfd6a388f251:0x84c23a83d202e7ee!8m2!3d56.9479283!4d24.1109812!10e9!16s%2Fg%2F11_j_8v3m?entry=ttu',
    sourceLabel: 'Runcis krogs — venue-uploaded May 2026 menu photo',
    sourceType: 'Verificēta aktuālā alus karte',
    beerPrices: [
      { name: 'Tērvetes gaišais (draft)', volumeMl: 500, price: 5.3 },
      { name: 'Tērvetes tumšais (draft)', volumeMl: 500, price: 5.3 },
      { name: 'Ķiršu alus (draft)', volumeMl: 500, price: 5.3 },
      { name: 'Madonas nefiltrētais (draft)', volumeMl: 500, price: 6.5 },
    ],
    hours: {
      mon: ['16:00-22:30'], tue: ['16:00-23:00'], wed: ['14:00-00:30'], thu: ['14:00-00:00'],
      fri: ['14:00-03:00'], sat: ['14:00-00:00'], sun: ['14:00-23:30'],
      sourceUrl: 'https://www.google.com/maps/place/Runcis-krogs/@56.9479283,24.1109812,17z/data=!4m6!3m5!1s0x46eecfd6a388f251:0x84c23a83d202e7ee!8m2!3d56.9479283!4d24.1109812!16s%2Fg%2F11_j_8v3m',
    },
    evidenceNotes: 'The May 2026 menu-board photo was uploaded by the venue to its Google Maps listing and publishes named draft beers, exact serving sizes and prices. The branch listing supplies the exact address, coordinates and business-updated weekly hours. The generic non-alcoholic beer row was excluded because no beer name or serving size is published.',
  },
  {
    id: 'vertigo-jumta-bars',
    name: 'Vertigo jumta bārs',
    kind: 'jumta bārs',
    address: '13. janvāra iela 8, Rīga, LV-1050',
    lat: 56.946103,
    lng: 24.1160199,
    sourceUrl: 'https://www.tripadvisor.com/Restaurant_Review-g274967-d10347314-Reviews-Vertigo-Riga_Riga_Region.html',
    sourceLabel: 'Vertigo — current business-managed menu and listing',
    sourceType: 'Verificēta aktuālā alus karte',
    beerPrices: [
      { name: 'SOL', volumeMl: 330, price: 4.5 },
      { name: 'Lielvārdes gaišais', volumeMl: 500, price: 5.8 },
      { name: 'Madonas gaišais', volumeMl: 500, price: 5.8 },
      { name: 'Bauskas gaišais speciālais', volumeMl: 500, price: 5.8 },
      { name: 'Bauskas tumšais speciālais', volumeMl: 500, price: 5.8 },
    ],
    hours: {
      mon: ['16:00-21:30'], tue: ['16:00-21:30'], wed: ['16:00-21:30'], thu: ['16:00-21:30'],
      fri: ['16:00-22:30'], sat: ['16:00-22:30'], sun: ['16:00-21:30'],
      sourceUrl: 'https://www.tripadvisor.com/Restaurant_Review-g274967-d10347314-Reviews-Vertigo-Riga_Riga_Region.html',
    },
    evidenceNotes: 'The current claimed and business-managed venue listing identifies Vertigo as a dedicated rooftop bar and publishes its complete Beer / Cider section with exact beer names, serving sizes and prices; cider was excluded. The live listing also supplies the exact address and weekly hours. Coordinates resolve to the Vertigo venue inside Forum Cinemas at the published address.',
  },
  {
    id: 'the-13-bar',
    name: 'THE 13 BAR',
    kind: 'sporta bārs',
    address: 'Tērbatas iela 40, Rīga, LV-1011',
    lat: 56.9555399,
    lng: 24.1255712,
    sourceUrl: 'https://menu02.restaurantguru.com/m1/menu-THE-13-BAR-d54.jpg',
    sourceLabel: 'THE 13 BAR — current drinks-menu photo',
    sourceType: 'Verificēta aktuālā alus karte',
    beerPrices: [
      { name: 'Heniken', volumeMl: null, price: 3.5 },
      { name: 'Heniken B/A', volumeMl: null, price: 3.5 },
      { name: 'Sol', volumeMl: null, price: 3.5 },
      { name: 'Lielvārdes gaišais', volumeMl: null, price: 5 },
      { name: 'Bauskas gaišais', volumeMl: null, price: 5 },
      { name: 'Lielvārdes ķiršu', volumeMl: null, price: 5.5 },
      { name: 'Lielvārdes tumšais', volumeMl: null, price: 5.5 },
      { name: 'Madonas nefiltrētais', volumeMl: null, price: 6 },
      { name: 'Anarkist New England IPA', volumeMl: null, price: 6 },
    ],
    hours: {
      mon: ['11:00-22:00'], tue: ['11:00-22:00'], wed: ['11:00-22:00'], thu: ['11:00-22:00'],
      fri: ['11:00-00:00'], sat: ['11:00-00:00'], sun: ['11:00-22:00'],
      sourceUrl: 'https://www.tripadvisor.com/Restaurant_Review-g274967-d27974154-Reviews-The_13_Bar-Riga_Riga_Region.html',
    },
    evidenceNotes: 'The current drinks-menu photo is labelled as added four months ago and publishes nine exact beer prices. The menu does not print serving sizes, so every volume is deliberately recorded as unknown. The current claimed Tripadvisor listing identifies the venue as a Bar/Pub and publishes its weekly hours; current sports-viewing listings corroborate the active nine-screen sports bar at this exact address. Beer spelling is preserved from the printed menu.',
  },
  {
    id: 'purple-haze-riga',
    name: 'Purple Haze',
    kind: 'kokteiļu un ūdenspīpju bārs',
    address: 'Augusta Deglava iela 82, Rīga, LV-1035',
    lat: 56.949466,
    lng: 24.181174,
    sourceUrl: 'https://menu.ps.me/HVCZJCyuxk4',
    sourceLabel: 'Purple Haze — official live owner menu',
    sourceType: official,
    beerPrices: [
      { name: 'Corona Extra', volumeMl: null, price: 4.5 },
      { name: 'Valmiermuiža', volumeMl: null, price: 6 },
      { name: 'Raiskumietis', volumeMl: null, price: 6 },
    ],
    hours: {
      mon: ['16:00-00:00'], tue: ['16:00-00:00'], wed: ['16:00-00:00'], thu: ['16:00-00:00'],
      fri: ['16:00-02:00'], sat: ['16:00-02:00'], sun: ['16:00-00:00'],
      sourceUrl: 'https://www.waze.com/live-map/directions/lv/riga/purple-haze?to=place.ChIJdSaUqxPO7kYRkFxpMc59TK0',
    },
    evidenceNotes: 'The live owner-controlled Poster menu identifies Purple Haze at Augusta Deglava iela 82 and publishes the complete Beer category: Corona Extra EUR 4.50, Valmiermuiža EUR 6.00, and Raiskumietis EUR 6.00. No serving sizes are published, so volumes are deliberately unknown. Current Waze hours match the March 2026-updated RestaurantGuru listing. Coordinates resolve to the published venue building.',
  },
  {
    id: 'cosmos-rest-bar-riga',
    name: 'Cosmos Riga Rest Bar',
    kind: 'kokteiļu un ūdenspīpju bārs',
    address: 'Latgales iela 256A, Rīga, LV-1063',
    lat: 56.91211,
    lng: 24.176807,
    sourceUrl: 'https://menu.ps.me/S3JLwqzCg3I',
    sourceLabel: 'Cosmos Riga Rest Bar — official live owner menu',
    sourceType: official,
    beerPrices: [
      { name: 'Ķiršu alus', volumeMl: null, price: 5.5 },
      { name: 'Corona', volumeMl: 355, price: 5 },
      { name: 'Corona Cero 0.0%', volumeMl: 330, price: 5 },
      { name: 'Valmiermuižas gaišais', volumeMl: 500, price: 6.5 },
      { name: 'Tērvetes', volumeMl: 500, price: 6 },
      { name: 'Užavas gaišais', volumeMl: 500, price: 6.5 },
    ],
    hours: {
      mon: ['15:00-00:00'], tue: ['15:00-00:00'], wed: ['15:00-00:00'], thu: ['15:00-00:00'],
      fri: ['15:00-02:00'], sat: ['15:00-02:00'], sun: ['15:00-00:00'],
      sourceUrl: 'https://restaurantguru.com/Cosmos-Restbar-Riga',
    },
    evidenceNotes: 'The current owner-controlled Poster menu identifies COSMOS REST BAR Rīga and publishes the complete Alus category with six beer items, exact prices, and stated sizes where available. Ķiršu alus has no printed serving size, so its volume is deliberately unknown; Rekorderlig was excluded as cider. The official menu still uses the former Maskavas iela street name, while current address records identify the renamed Latgales iela 256A. Current venue listings corroborate the bar category, active status and weekly hours; coordinates resolve to the exact published building.',
  },
  {
    id: 'elpa-teika',
    name: 'elpa',
    kind: 'kokteiļu bārs',
    address: 'Brīvības gatve 316, Rīga, LV-1006',
    lat: 56.9792169,
    lng: 24.1871875,
    sourceUrl: 'https://www.google.com/maps/place/elpa/@56.9794369,24.1870307,3a,75y,90t/data=!3m8!1e2!3m6!1sCIABIhDbgFuLp9dZVUwkdVgtiHVd!2e10!3e12!6shttps:%2F%2Flh3.googleusercontent.com%2Fgps-cs-s%2FAHRPTWkpHaMbxgDzrzcom80VqpS_rXuPXGx1qd8oOYzbUrc_8J6DIQ9iYjj0Q5A9359gnqCMsIg7rCB909Fk9Q1pkJuX5LbKma4GCdXZaET5PWA1cy1reayJFqxRhVSiUECU9QjmiPd1Y3sUSD-d%3Dw137-h195-k-no!7i1055!8i1491!4m7!3m6!1s0x46eecf003bed13c7:0x9e064143e19a953f!8m2!3d56.9792169!4d24.1871875!10e9!16s%2Fg%2F11vq9n5677?entry=ttu',
    sourceLabel: 'elpa — venue-uploaded August 2026 Google menu',
    sourceType: 'Verificēta aktuālā alus karte',
    beerPrices: [
      { name: 'Mežpils', volumeMl: 400, price: 5 },
      { name: 'Corona', volumeMl: 400, price: 5 },
      { name: 'Kronenbourg 1664 Blanc', volumeMl: 400, price: 6 },
    ],
    hours: {
      mon: ['16:00-23:00'], tue: ['16:00-23:00'], wed: ['16:00-23:00'], thu: ['16:00-23:00'],
      fri: ['16:00-23:00'], sat: ['12:00-23:00'], sun: ['12:00-23:00'],
      sourceUrl: 'https://www.google.com/maps/place/elpa/@56.9792169,24.1871875,17z/data=!4m6!3m5!1s0x46eecf003bed13c7:0x9e064143e19a953f!8m2!3d56.9792169!4d24.1871875!16s%2Fg%2F11vq9n5677',
    },
    evidenceNotes: 'The live Google business listing identifies elpa as a bar. Its Menu view says the menu was uploaded by the venue profile in August 2026; the ALUS & SIDRS 0.4 L category publishes three named beers with exact prices. Somersby was excluded as cider and the generic Craft alus row was excluded because no beer name is published. The listing supplies the exact address, coordinates and current weekly hours.',
  },
  {
    id: 'nok-nok-restbar',
    name: 'NOK NOK Restbar',
    kind: 'restbārs un pasākumu bārs',
    address: 'Brīvības gatve 409, Rīga, LV-1024',
    lat: 56.989261,
    lng: 24.2375443,
    sourceUrl: 'https://noknok-restbar.lv/lv/menu/section:alus-un-sidrs',
    sourceLabel: 'NOK NOK Restbar — official live digital dine-in menu',
    sourceType: official,
    beerPrices: [
      { name: 'Valmiermuižas alus (draft)', volumeMl: 300, price: 4.5 },
      { name: 'Valmiermuižas alus (draft)', volumeMl: 500, price: 5.5 },
      { name: 'Iļģuciems Medalus oriģinālais (draft)', volumeMl: 300, price: 4.5 },
      { name: 'Iļģuciems Medalus oriģinālais (draft)', volumeMl: 500, price: 5.5 },
      { name: 'Iļģuciems Rīgas alus (draft)', volumeMl: 300, price: 4.2 },
      { name: 'Iļģuciems Rīgas alus (draft)', volumeMl: 500, price: 5 },
      { name: 'Leffe Blonde (draft)', volumeMl: 300, price: 5.7 },
      { name: 'Leffe Blonde (draft)', volumeMl: 500, price: 6.5 },
      { name: 'Valmiermuiža bezalkoholiskais alus', volumeMl: 500, price: 4.5 },
      { name: 'Valmiermuiža tumšais alus', volumeMl: 500, price: 5.5 },
      { name: 'Bauska gaišais alus', volumeMl: 500, price: 5 },
      { name: 'Valmiermuiža porteris', volumeMl: 300, price: 4.8 },
      { name: 'Corona Extra gaišais alus', volumeMl: 300, price: 4 },
    ],
    hours: {
      mon: ['11:00-22:00'], tue: ['11:00-22:00'], wed: ['11:00-22:00'], thu: ['11:00-22:00'],
      fri: ['11:00-05:00'], sat: ['12:00-05:00'], sun: ['12:00-22:00'],
      sourceUrl: 'https://noknok-restbar.lv/lv/',
    },
    evidenceNotes: 'The official live ChoiceQR dine-in menu identifies the venue and publishes the complete ALUS UN SIDRS category with exact option-level sizes and prices. Bumbieru dārza sidrs was excluded. The official site schedule supplies all weekly hours. NOK NOK is an event-led nightlife restbar open until 05:00 on Friday and Saturday, not merely an ordinary dining restaurant.',
  },
];

export const verifiedVenueDataPost150 = { venues };
